package org.egov.hc.utils;

import org.springframework.stereotype.Component;


@Component
public class HCConstants {
	
	private HCConstants() {}
	
	public static final String CITIZEN = "CITIZEN";
	
	
	public static final String TRUE = "true";
	
	//Scheduler
	
	public static final String OVERDAYS = "OVERDAYS";
	
	public static final String REMINDER = "REMINDER";
	
	public static final String MODULENAMEVALUE = "HORTICULTURE";
	
	//Roll
	
	public static final String ROLE = "EE";
	public static final String EXECUTIVE_ENGINEER = "EE";
	public static final String JUNIER_ENGINEERE = "JE";
	public static final String SDO = "SDO";
	
	// Actions
	
	public static final String SUBMITTED = "SUBMITTED";
	public static final String VERIFY_AND_FORWARD = "VERIFY AND FORWARD";
	public static final String VERIFY_AND_FORWARD_TO_SDO = "VERIFY AND FORWARD TO SDO";
	public static final String FORWARD_FOR_INSPECTION = "FORWARD FOR INSPECTION";
	public static final String EDIT = "EDIT";
	public static final String REJECT = "REJECT";
	public static final String INSPECT = "INSPECT";
	public static final String APPROVE = "APPROVE";
	public static final String REQUEST_CLARIFICATION = "REQUEST CLARIFICATION";
	public static final String COMPLETE = "COMPLETE";
	public static final String INITIATE = "INITIATE";
	public static final String ACTION_ASSIGN = "ASSIGN";
	
	//comment
	public static final String COMMENT = "your service has been rejected as service request type has been changed.";
	
	//Service Request STatus
	public static final String INITIATED_STATUS = "INITIATED";
	public static final String REJECTED_STATUS = "REJECTED";
	public static final String APPROVED_STATUS = "APPROVED";
	public static final String COMPLETED_STATUS = "COMPLETED";
	public static final String ASSIGNED_STATUS = "ASSIGNED";
	
	public static final String INSPECTED_STATUS = "INSPECTED";
	public static final String VERIFYANDFORWARD = "VERIFYANDFORWARD";
	public static final String REVIEW = "REVIEW";
	public static final String REJECTED = "REJECTED";
	public static final String ACTION_OPEN = "open";
	
	//Notification type
	public static final String SMS = "sms";
	public static final String EMAIL = "email";
	public static final String PUSH = "push";

	//Device_source_detail
	
	public static final String DEVICE_HORTICULTURE = "raise service request";
	public static final String MODULE_CODE = "HC";
	
	// Massage
	
	public static final String SUCCESS = "success";
	public static final String MEDIA = "media";

	
	public static final String ACTION_UPDATE  = "UPDATE";
	
	public static final String LOCALIZATION_MODULE_NAME = "rainmaker-hc";

	public static final String EMPLOYEE_NAME_JSONPATH = "$.Employees[0].user.name";
	public static final String EMPLOYEE_PHNO_JSONPATH = "$.Employees[0].user.mobileNumber"; 
	
	public static final String EMPLOYEE_EMAILID_JSONPATH = "$.Employees[0].user.emailId";

	public static final String LOCALIZATION_CODES_JSONPATH = "$.messages.*.code";
	public static final String LOCALIZATION_MSGS_JSONPATH = "$.messages.*.message";

	
	//SMS
	
	public static final String HC_CITIZEN_SUBMITREQUEST_SMS_NOTIFICATION="HC_CITIZEN_SUBMITREQUEST_SMS_NOTIFICATION";
	public static final String HC_CITIZEN_REJECTSERVICEREQUEST_SMS_NOTIFICATION="HC_CITIZEN_REJECTSERVICEREQUEST_SMS_NOTIFICATION";
	public static final String HC_CITIZEN_SERVICEREQUESTCOMPLETED_SMS_NOTIFICATION="HC_CITIZEN_SERVICEREQUESTCOMPLETED_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_VERIFYANDFORWARD_SMS_NOTIFICATION="HC_EMPLOYEE_VERIFYANDFORWARD_SMS_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_INITIATE_SMS_NOTIFICATION="HC_CITIZEN_REQUEST_INITIATE_SMS_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_UPDATE_SMS_NOTIFICATION="HC_CITIZEN_REQUEST_UPDATE_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_SERVICEREQUEST_SMS_NOTIFICATION="HC_EMPLOYEE_SERVICEREQUEST_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_ACTION_APPROVE_SMS_NOTIFICATION="HC_EMPLOYEE_ACTION_APPROVE_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_ACTION_ASSIGN_SMS_NOTIFICATION="HC_EMPLOYEE_ACTION_ASSIGN_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_REQUEST_SMS_NOTIFICATION="HC_EMPLOYEE_REQUEST_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_FORWARD_TO_SDO_SMS_NOTIFICATION="HC_EMPLOYEE_FORWARD_TO_SDO_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_INSPECTION_SMS_NOTIFICATION="HC_EMPLOYEE_INSPECTION_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_CLARIFICATION_SMS_NOTIFICATION="HC_EMPLOYEE_CLARIFICATION_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_INSPECT_SMS_NOTIFICATION="HC_EMPLOYEE_INSPECT_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_REQUEST_FORWARD_SMS_NOTIFICATION="HC_EMPLOYEE_REQUEST_FORWARD_SMS_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_FOR_UPDATE_SMS_NOTIFICATION="HC_CITIZEN_REQUEST_FOR_UPDATE_SMS_NOTIFICATION";
	
	//EMAIL
	public static final String HC_CITIZEN_SUBMITREQUEST_EMAIL_NOTIFICATION="HC_CITIZEN_SUBMITREQUEST_EMAIL_NOTIFICATION";
	public static final String HC_CITIZEN_REJECTSERVICEREQUEST_EMAIL_NOTIFICATION="HC_CITIZEN_REJECTSERVICEREQUEST_EMAIL_NOTIFICATION";
	public static final String HC_CITIZEN_SERVICEREQUESTCOMPLETED_EMAIL_NOTIFICATION="HC_CITIZEN_SERVICEREQUESTCOMPLETED_EMAIL_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_INITIATE_EMAIL_NOTIFICATION="HC_CITIZEN_REQUEST_INITIATE_EMAIL_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_UPDATE_EMAIL_NOTIFICATION="HC_CITIZEN_REQUEST_UPDATE_EMAIL_NOTIFICATION";
	public static final String HC_EMPLOYEE_REQUEST_EMAIL_NOTIFICATION="HC_EMPLOYEE_REQUEST_EMAIL_NOTIFICATION";
	public static final String HC_EMPLOYEE_ACTION_APPROVE_EMAIL_NOTIFICATION="HC_EMPLOYEE_ACTION_APPROVE_EMAIL_NOTIFICATION";
	public static final String HC_EMPLOYEE_ACTION_ASSIGN_EMAIL_NOTIFICATION="HC_EMPLOYEE_ACTION_ASSIGN_EMAIL_NOTIFICATION";
	public static final String HC_EMPLOYEE_FORWARD_TO_SDO_EMAIL_NOTIFICATION="HC_EMPLOYEE_FORWARD_TO_SDO_EMAIL_NOTIFICATION";
	public static final String HC_EMPLOYEE_INSPECTION_EMAIL_NOTIFICATION="HC_EMPLOYEE_INSPECTION_EMAIL_NOTIFICATION";
	public static final String HC_EMPLOYEE_INSPECT_EMAIL_SUBJECT_NOTIFICATION="HC_EMPLOYEE_INSPECT_EMAIL_SUBJECT_NOTIFICATION";
	public static final String HC_EMPLOYEE_INSPECT_EMAIL_NOTIFICATION="HC_EMPLOYEE_INSPECT_EMAIL_NOTIFICATION";
	public static final String HC_EMPLOYEE_REQUEST_FORWARD_EMAIL_NOTIFICATION="HC_EMPLOYEE_REQUEST_FORWARD_EMAIL_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_FOR_UPDATE_EMAIL_NOTIFICATION="HC_CITIZEN_REQUEST_FOR_UPDATE_EMAIL_NOTIFICATION";
	
	
	//EMAIL SUBJECT
	public static final String HC_CITIZEN_REQUEST_EMAIL_SUBJECT_ACTION_ASSIGN="HC_CITIZEN_REQUEST_EMAIL_SUBJECT_ACTION_ASSIGN";
	public static final String HC_CITIZEN_REQUEST_EMAIL_SUBJECT_ACTION_REJECT="HC_CITIZEN_REQUEST_EMAIL_SUBJECT_ACTION_REJECT";
	public static final String HC_CITIZEN_REQUEST_EMAIL_SUBJECT_ACTION_COMPLETE="HC_CITIZEN_REQUEST_EMAIL_SUBJECT_ACTION_COMPLETE";
	public static final String HC_CITIZEN_REQUEST_EMAIL_SUBJECT_ACTION_OPEN="HC_CITIZEN_REQUEST_EMAIL_SUBJECT_ACTION_OPEN";
	public static final String HC_EMPLOYEE_ACTION_APPROVE_EMAIL_SUBJECT = "HC_EMPLOYEE_ACTION_APPROVE_EMAIL_SUBJECT";
	public static final String HC_EMPLOYEE_ACTION_ASSIGN_EMAIL_SUBJECT = "HC_EMPLOYEE_ACTION_ASSIGN_EMAIL_SUBJECT";
	public static final String HC_EMPLOYEE_FORWARD_TO_SDO_EMAIL_SUBJECT = "HC_EMPLOYEE_FORWARD_TO_SDO_EMAIL_SUBJECT";
	public static final String HC_EMPLOYEE_INSPECTION_EMAIL_SUBJECT = "HC_EMPLOYEE_INSPECTION_EMAIL_SUBJECT";
	public static final String HC_EMPLOYEE_CLARIFICATION_EMAIL_SUBJECT = "HC_EMPLOYEE_CLARIFICATION_EMAIL_SUBJECT";
	public static final String HC_CITIZEN_REQUEST_EMAIL_SUBJECT_ACTION_UPDATE = "HC_CITIZEN_REQUEST_EMAIL_SUBJECT_ACTION_UPDATE";
	public static final String HC_EMPLOYEE_REQUEST_EMAIL_SUBJECT="HC_EMPLOYEE_REQUEST_EMAIL_SUBJECT";
	public static final String HC_EMPLOYEE_FORWARDREQUEST_EMAIL_SUBJECT="HC_EMPLOYEE_FORWARDREQUEST_EMAIL_SUBJECT";
	public static final String HC_EMPLOYEE_CLARIFICATION_EMAIL_NOTIFICATION="HC_EMPLOYEE_CLARIFICATION_EMAIL_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_FOR_UPDATE_EMAIL_NOTIFICATION_SUBJECT="HC_CITIZEN_REQUEST_FOR_UPDATE_EMAIL_NOTIFICATION_SUBJECT";
	
	//PUSH
	public static final String HC_EMPLOYEE_SERVICEREQUEST_PUSH_NOTIFICATION="HC_EMPLOYEE_SERVICEREQUEST_PUSH_NOTIFICATION";
	public static final String HC_EMPLOYEE_SERVICEREQUEST_EMAIL_NOTIFICATION="HC_EMPLOYEE_SERVICEREQUEST_EMAIL_NOTIFICATION";
	public static final String HC_CITIZEN_REJECTSERVICEREQUEST_PUSH_NOTIFICATION="HC_CITIZEN_REJECTSERVICEREQUEST_PUSH_NOTIFICATION";
	public static final String HC_CITIZEN_SERVICEREQUESTCOMPLETED_PUSH_NOTIFICATION="HC_CITIZEN_SERVICEREQUESTCOMPLETED_PUSH_NOTIFICATION";
	public static final String HC_EMPLOYEE_REQUEST_PUSH_NOTIFICATION="HC_EMPLOYEE_REQUEST_PUSH_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_UPDATE_PUSH_NOTIFICATION="HC_CITIZEN_REQUEST_UPDATE_PUSH_NOTIFICATION";
	public static final String HC_EMPLOYEE_INSPECT_PUSH_NOTIFICATION="HC_EMPLOYEE_INSPECT_PUSH_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_PUSH_NOTIFICATION="HC_CITIZEN_REQUEST_PUSH_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_INITIATE_PUSH_NOTIFICATION="HC_CITIZEN_REQUEST_INITIATE_PUSH_NOTIFICATION";
	public static final String HC_EMPLOYEE_ACTION_APPROVE_PUSH_NOTIFICATION="HC_EMPLOYEE_ACTION_APPROVE_PUSH_NOTIFICATION";
	public static final String HC_EMPLOYEE_ACTION_ASSIGN_PUSH_NOTIFICATION="HC_EMPLOYEE_ACTION_ASSIGN_PUSH_NOTIFICATION";
	public static final String HC_EMPLOYEE_FORWARD_TO_SDO_PUSH_NOTIFICATION="HC_EMPLOYEE_FORWARD_TO_SDO_PUSH_NOTIFICATION";
	public static final String HC_EMPLOYEE_INSPECTION_PUSH_NOTIFICATION="HC_EMPLOYEE_INSPECTION_PUSH_NOTIFICATION";
	public static final String HC_EMPLOYEE_CLARIFICATION_PUSH_NOTIFICATION="HC_EMPLOYEE_CLARIFICATION_PUSH_NOTIFICATION";
	public static final String HC_CITIZEN_SUBMITREQUEST_PUSH_NOTIFICATION="HC_CITIZEN_SUBMITREQUEST_PUSH_NOTIFICATION";
	public static final String HC_EMPLOYEE_REQUEST_FORWARD_PUSH_NOTIFICATION="HC_EMPLOYEE_REQUEST_FORWARD_PUSH_NOTIFICATION";
	public static final String HC_CITIZEN_REQUEST_FOR_UPDATE_PUSH_NOTIFICATION="HC_CITIZEN_REQUEST_FOR_UPDATE_PUSH_NOTIFICATION";
	
	//REMAINSER/OVERDAYS NOTIFICATION
	
	public static final String HC_EMPLOYEE_REMAINDER_SMS_NOTIFICATION="HC_EMPLOYEE_REMAINDER_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_OVERDAYS_SMS_NOTIFICATION="HC_EMPLOYEE_OVERDAYS_SMS_NOTIFICATION";
	public static final String HC_EMPLOYEE_OVERDAYS_EMAIL_NOTIFICATION="HC_EMPLOYEE_OVERDAYS_EMAIL_NOTIFICATION";
	public static final String HC_EMPLOYEE_REMAINDER_EMAIL_NOTIFICATION="HC_EMPLOYEE_REMAINDER_EMAIL_NOTIFICATION";
	public static final String HC_EMPLOYEE_OVERDAYS_PUSH_NOTIFICATION="HC_EMPLOYEE_OVERDAYS_PUSH_NOTIFICATION";
	public static final String HC_EMPLOYEE_REMAINDER_PUSH_NOTIFICATION="HC_EMPLOYEE_REMAINDER_PUSH_NOTIFICATION";
	
	//REMAINSER/OVERDAYS EMAIL SUBJECT 
	
	public static final String HC_EMPLOYEE_REMAINDER_EMAIL_SUBJECT="HC_EMPLOYEE_REMAINDER_EMAIL_SUBJECT";
	public static final String HC_EMPLOYEE_OVERDAYS_EMAIL_SUBJECT="HC_EMPLOYEE_OVERDAYS_EMAIL_SUBJECT";
	
	
	
	//approve, request for clarification
	
	public static final String SMS_NOTIFICATION_STATUS_KEY = "<status>";
	public static final String SMS_NOTIFICATION_COMPLAINT_TYPE_KEY = "<complaint_type>";
	public static final String SMS_NOTIFICATION_DATE_KEY = "<date>";
	public static final String SMS_NOTIFICATION_ID_KEY = "<id>";
	public static final String SMS_NOTIFICATION_EMP_NAME_KEY = "<emp_name>";
	public static final String SMS_NOTIFICATION_USER_NAME_KEY = "<citizen_name>";
	public static final String SMS_NOTIFICATION_SERVICEREQUEST_ID = "<service_request_id>";
	public static final String SMS_NOTIFICATION_SERVICEREQUEST_TYPE = "<service_request_type>";
	public static final String NOTIFICATION_SERVICEREQUEST_ID_NEW = "<service_request_id_new>";
	
		
	public static final String SMS_NOTIFICATION_SERVICEREQUEST_DATE_KEY = "<service_request_date>";
	public static final String  USREVENTS_EVENT_TYPE = "SYSTEMGENERATED";
	public static final String  USREVENTS_EVENT_NAME = "Horticulture Service Request";
	public static final String  USREVENTS_EVENT_POSTEDBY = "SYSTEM-HC";
	public static final String SMS_NOTIFICATION_SERVICEREQUEST_DAYS_KEY = "<days>";

	
	
	/*  search on roles constant */

	public static final String ROLE_EMPLOYEE = "EMPLOYEE";
	public static final String ROLE_CITIZEN = "CITIZEN";
	public static final String ROLE_GRO = "GRO";
	public static final String ROLE_DGRO = "DGRO";
	public static final String ROLE_CSR = "CSR";
	
	
	public static final String ROLE_NAME_CITIZEN = "Citizen";
	public static final String ROLE_NAME_EMPLOYEE = "Employee";
	public static final String ROLE_NAME_GRO = "Grievance Routing Officer";
	public static final String ROLE_NAME_DGRO = "Department Grievance Routing Officer";
	public static final String ROLE_NAME_CSR = "Customer Support Representative";
	public static final String SUBJECT = "SERVICE REQUEST FORM";
		
}