
CREATE TABLE public.nulm_susv_application_detail
(
  application_uuid character varying(64) NOT NULL,
  application_id character varying(64) NOT NULL,
  nulm_application_id character varying(64),
  application_status character varying(64),
  name_of_applicant character varying(255),
  gender character varying(255),
  age integer,
  adhar_no character varying(20),
  mother_name character varying(255),
  father_or_husband_name character varying(255),
  permanent_address character varying(255),
  present_address character varying(255),
  mobile_no character varying(255),
  is_disability boolean,
  category character varying(255),
  qualification character varying(255),
  blood_group character varying(255),
  category_of_vending character varying(255),
  proposed_location_of_vending character varying(255),
  proposed_time_of_vending character varying(255),
  goverment_scheme character varying(255),
  name_of_nominee character varying(255),
  tenant_id character varying(256),
  remark character varying(256),
  is_active boolean,
  is_undertaking boolean,
  date timestamp without time zone,
  place character varying(256),
  created_by character varying(64),
  created_time bigint,
  last_modified_by character varying(64),
  last_modified_time bigint,
  CONSTRAINT nulm_susv_application_detail_pkey PRIMARY KEY (application_uuid),
  CONSTRAINT susv_application_id UNIQUE (application_id)
)