
CREATE TABLE public.nulm_suh_application_detail
(
  suh_uuid character varying(256) NOT NULL,
  suh_id character varying(256),
  nulm_application_id character varying(64),
  name_of_shelter character varying(256),
  address character varying(256),
  shelter_background character varying(256),
  category character varying(256),
  weather_condition character varying(256),
  shelter_classification character varying(256),
  other_classification character varying(256),
  ownership character varying(256),
  operation_and_management_of_shelters character varying(256),
  area character varying(256),
  capacity character varying(256),
  is_constitution_of_shelter_management_committee boolean,
  constitution_of_shelter_management_committee_remark character varying(256),
  is_social_audit boolean,
  social_audit_remark character varying(256),
  is_linkage_to_central_govt_welfare_schemes boolean,
  linkage_to_central_govt_welfare_schemes_remark character varying(256),
  is_linkage_to_public_health_initiatives boolean,
  linkage_to_public_health_initiatives_remark character varying(256),
  is_linkage_to_other_govt_schemes boolean,
  linkage_to_other_govt_schemes_remark character varying(256),
  is_linkage_to_local_community boolean,
  linkage_to_local_community_remark character varying(256),
  is_linkage_to_social_workers_and_philanthropists boolean,
  linkage_to_social_workers_and_philanthropists_remark character varying(256),
  is_user_charges boolean,
  user_charges_remark character varying(256),
  is_iec_and_promotional_initiatives boolean,
  iec_and_promotional_initiatives_remark character varying(256),
  is_quarterly_reporting boolean,
  quarterly_reporting_remark character varying(256),
  is_visits boolean,
  visits_remark character varying(256),
  address_picture json,
  program_picture json,
  document_attachment json,
  remark character varying(256),
  application_status character varying(256),
  tenant_id character varying(256) NOT NULL,
  is_active boolean,
  created_by character varying(64),
  created_time bigint,
  last_modified_by character varying(64),
  last_modified_time bigint,
  CONSTRAINT nulm_suh_application_detail_pkey PRIMARY KEY (suh_uuid)
)