
CREATE TABLE public.nulm_suh_facilities_maintenance
(
  suh_uuid character varying(256),
  facility_uuid character varying(256) NOT NULL,
  is_bedding boolean,
  bedding_remark character varying(256),
  is_washing_of_linen boolean,
  washing_of_linen_remark character varying(256),
  is_cleaning_of_premises boolean,
  cleaning_of_premise_remark character varying(256),
  is_recreation_facilities boolean,
  recreation_facilities_remark character varying(256),
  is_drinking_water boolean,
  drinking_water_remark character varying(256),
  is_meals boolean,
  meals_remark character varying(256),
  is_locker_for_inmates boolean,
  locker_for_inmates_remark character varying(256),
  is_fire_safety_measure boolean,
  fire_safety_measure_remark character varying(256),
  is_office_set_up boolean,
  office_set_up_remark character varying(256),
  is_first_aid_kit_and_training_to_staff boolean,
  first_aid_kit_and_training_to_staff_remark character varying(256),
  is_display_of_emergency_numbers boolean,
  display_of_emergency_numbers_remark character varying(256),
  is_toilet boolean,
  toilet_remark character varying(256),
  facility_picture json,
  tenant_id character varying(256) NOT NULL,
  is_active boolean,
  created_by character varying(64),
  created_time bigint,
  last_modified_by character varying(64),
  last_modified_time bigint,
  CONSTRAINT nulm_suh_facilities_maintenance_pkey PRIMARY KEY (facility_uuid)
)